services:
  - type: web
    name: telegram-webhook-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        value: "8138103593:AAGXULM2s5JGiQYhXWCd_7ejW4j6iocbw54"
      - key: CHAT_ID
        value: "5573666747"
