services:
  - type: web
    name: telegram-webhook-bot
    env: python
    repo: https://github.com/ammoyek/telegram-webhook-bot
    branch: main
    buildCommand: ""
    startCommand: python main.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        value: senin_bot_tokenin
      - key: CHAT_ID
        value: senin_chat_idn
